do {
  raise "boom"
} rescue {
  case err => {
    print(err)
    "handled"
  }
}
